//ACTION --> DESCRIBES WHAT YOU WANT TO DO
//DEFINE CONSTANTS THAT DEFINE ACTIONS
//THIS FILE IS A CENTRALIZED PLACE TO VIEW ALL YOUR TYPES IN ONE PLACE

export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const FETCH_TASK = 'FETCH_TASK';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';



